//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace FuncionarioApp.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FuncionariosSoap", Namespace="http://tempuri.org/")]
    public partial class Funcionarios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterFuncionariosPorSexoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Funcionarios() {
            this.Url = global::FuncionarioApp.Properties.Settings.Default.FuncionarioApp_localhost_Funcionarios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterFuncionariosPorSexoCompletedEventHandler ObterFuncionariosPorSexoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterFuncionariosPorSexo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("xml", IsNullable=true)]
        public xml ObterFuncionariosPorSexo(string sexo) {
            object[] results = this.Invoke("ObterFuncionariosPorSexo", new object[] {
                        sexo});
            return ((xml)(results[0]));
        }
        
        /// <remarks/>
        public void ObterFuncionariosPorSexoAsync(string sexo) {
            this.ObterFuncionariosPorSexoAsync(sexo, null);
        }
        
        /// <remarks/>
        public void ObterFuncionariosPorSexoAsync(string sexo, object userState) {
            if ((this.ObterFuncionariosPorSexoOperationCompleted == null)) {
                this.ObterFuncionariosPorSexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterFuncionariosPorSexoOperationCompleted);
            }
            this.InvokeAsync("ObterFuncionariosPorSexo", new object[] {
                        sexo}, this.ObterFuncionariosPorSexoOperationCompleted, userState);
        }
        
        private void OnObterFuncionariosPorSexoOperationCompleted(object arg) {
            if ((this.ObterFuncionariosPorSexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterFuncionariosPorSexoCompleted(this, new ObterFuncionariosPorSexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class xml {
        
        private Funcionario[] funcionariosField;
        
        /// <remarks/>
        public Funcionario[] funcionarios {
            get {
                return this.funcionariosField;
            }
            set {
                this.funcionariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Funcionario {
        
        private string idt_funcField;
        
        private string cpfField;
        
        private string nomeField;
        
        private string rgField;
        
        private string emailField;
        
        private string tel_residencialField;
        
        private string tel_celularField;
        
        private string data_nascimentoField;
        
        private string sexoField;
        
        /// <remarks/>
        public string idt_func {
            get {
                return this.idt_funcField;
            }
            set {
                this.idt_funcField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string tel_residencial {
            get {
                return this.tel_residencialField;
            }
            set {
                this.tel_residencialField = value;
            }
        }
        
        /// <remarks/>
        public string tel_celular {
            get {
                return this.tel_celularField;
            }
            set {
                this.tel_celularField = value;
            }
        }
        
        /// <remarks/>
        public string data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                this.data_nascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObterFuncionariosPorSexoCompletedEventHandler(object sender, ObterFuncionariosPorSexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterFuncionariosPorSexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterFuncionariosPorSexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public xml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((xml)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591